/*
 * File: app/view/scan/Learn.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QDT.view.scan.Learn', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.button.Button'
    ],

    height: 307,
    width: 516,
    layout: 'fit',
    title: '学习(Learn)',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'container',
                                    columnWidth: 0.49,
                                    margin: '5 5 5 5 ',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: '学习项目信息',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: '编号',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '员工',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '项目',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '工序',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '类型',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '状态',
                                                    labelWidth: 50
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    columnWidth: 0.49,
                                    margin: '5 5 5 5 ',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: '具体信息',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: '设备号',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '类型',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    anchor: '100%',
                                                    fieldLabel: '进度',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '师傅',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'hiddenfield',
                                                    anchor: '100%',
                                                    fieldLabel: '序列号',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: '序列号',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    anchor: '100%',
                                                    fieldLabel: '零件号',
                                                    labelWidth: 50
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '5 5 5 5 ',
                                    text: '重置'
                                },
                                {
                                    xtype: 'button',
                                    margins: '5 0 5 5 ',
                                    text: '提交'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});