//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SystemAdminEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SystemAdminEntities object using the connection string found in the 'SystemAdminEntities' section of the application configuration file.
        /// </summary>
        public SystemAdminEntities() : base("name=SystemAdminEntities", "SystemAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SystemAdminEntities object.
        /// </summary>
        public SystemAdminEntities(string connectionString) : base(connectionString, "SystemAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SystemAdminEntities object.
        /// </summary>
        public SystemAdminEntities(EntityConnection connection) : base(connection, "SystemAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_dept> sys_dept
        {
            get
            {
                if ((_sys_dept == null))
                {
                    _sys_dept = base.CreateObjectSet<sys_dept>("sys_dept");
                }
                return _sys_dept;
            }
        }
        private ObjectSet<sys_dept> _sys_dept;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_strings> sys_strings
        {
            get
            {
                if ((_sys_strings == null))
                {
                    _sys_strings = base.CreateObjectSet<sys_strings>("sys_strings");
                }
                return _sys_strings;
            }
        }
        private ObjectSet<sys_strings> _sys_strings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_menu> sys_menu
        {
            get
            {
                if ((_sys_menu == null))
                {
                    _sys_menu = base.CreateObjectSet<sys_menu>("sys_menu");
                }
                return _sys_menu;
            }
        }
        private ObjectSet<sys_menu> _sys_menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_user> sys_user
        {
            get
            {
                if ((_sys_user == null))
                {
                    _sys_user = base.CreateObjectSet<sys_user>("sys_user");
                }
                return _sys_user;
            }
        }
        private ObjectSet<sys_user> _sys_user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_attachment> sys_attachment
        {
            get
            {
                if ((_sys_attachment == null))
                {
                    _sys_attachment = base.CreateObjectSet<sys_attachment>("sys_attachment");
                }
                return _sys_attachment;
            }
        }
        private ObjectSet<sys_attachment> _sys_attachment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_attachment_ref> sys_attachment_ref
        {
            get
            {
                if ((_sys_attachment_ref == null))
                {
                    _sys_attachment_ref = base.CreateObjectSet<sys_attachment_ref>("sys_attachment_ref");
                }
                return _sys_attachment_ref;
            }
        }
        private ObjectSet<sys_attachment_ref> _sys_attachment_ref;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_program> sys_program
        {
            get
            {
                if ((_sys_program == null))
                {
                    _sys_program = base.CreateObjectSet<sys_program>("sys_program");
                }
                return _sys_program;
            }
        }
        private ObjectSet<sys_program> _sys_program;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_group_menu> sys_group_menu
        {
            get
            {
                if ((_sys_group_menu == null))
                {
                    _sys_group_menu = base.CreateObjectSet<sys_group_menu>("sys_group_menu");
                }
                return _sys_group_menu;
            }
        }
        private ObjectSet<sys_group_menu> _sys_group_menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_user_group> sys_user_group
        {
            get
            {
                if ((_sys_user_group == null))
                {
                    _sys_user_group = base.CreateObjectSet<sys_user_group>("sys_user_group");
                }
                return _sys_user_group;
            }
        }
        private ObjectSet<sys_user_group> _sys_user_group;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sys_user_menu> sys_user_menu
        {
            get
            {
                if ((_sys_user_menu == null))
                {
                    _sys_user_menu = base.CreateObjectSet<sys_user_menu>("sys_user_menu");
                }
                return _sys_user_menu;
            }
        }
        private ObjectSet<sys_user_menu> _sys_user_menu;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_dept EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_dept(sys_dept sys_dept)
        {
            base.AddObject("sys_dept", sys_dept);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_strings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_strings(sys_strings sys_strings)
        {
            base.AddObject("sys_strings", sys_strings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_menu(sys_menu sys_menu)
        {
            base.AddObject("sys_menu", sys_menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_user(sys_user sys_user)
        {
            base.AddObject("sys_user", sys_user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_attachment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_attachment(sys_attachment sys_attachment)
        {
            base.AddObject("sys_attachment", sys_attachment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_attachment_ref EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_attachment_ref(sys_attachment_ref sys_attachment_ref)
        {
            base.AddObject("sys_attachment_ref", sys_attachment_ref);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_program EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_program(sys_program sys_program)
        {
            base.AddObject("sys_program", sys_program);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_group_menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_group_menu(sys_group_menu sys_group_menu)
        {
            base.AddObject("sys_group_menu", sys_group_menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_user_group EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_user_group(sys_user_group sys_user_group)
        {
            base.AddObject("sys_user_group", sys_user_group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sys_user_menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosys_user_menu(sys_user_menu sys_user_menu)
        {
            base.AddObject("sys_user_menu", sys_user_menu);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="loginSSO">No Metadata Documentation available.</param>
        /// <param name="loginPWD">No Metadata Documentation available.</param>
        public ObjectResult<LoginUser> sysUserLoginSP(global::System.String loginSSO, global::System.String loginPWD)
        {
            ObjectParameter loginSSOParameter;
            if (loginSSO != null)
            {
                loginSSOParameter = new ObjectParameter("loginSSO", loginSSO);
            }
            else
            {
                loginSSOParameter = new ObjectParameter("loginSSO", typeof(global::System.String));
            }
    
            ObjectParameter loginPWDParameter;
            if (loginPWD != null)
            {
                loginPWDParameter = new ObjectParameter("loginPWD", loginPWD);
            }
            else
            {
                loginPWDParameter = new ObjectParameter("loginPWD", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<LoginUser>("sysUserLoginSP", loginSSOParameter, loginPWDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public ObjectResult<sys_user> sysGetUsersInfoSP(global::System.String id)
        {
            ObjectParameter idParameter;
            if (id != null)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<sys_user>("sysGetUsersInfoSP", idParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="id">No Metadata Documentation available.</param>
        public ObjectResult<sys_user> sysGetUsersInfoSP(global::System.String id, MergeOption mergeOption)
        {
            ObjectParameter idParameter;
            if (id != null)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<sys_user>("sysGetUsersInfoSP", mergeOption, idParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="user_id">No Metadata Documentation available.</param>
        /// <param name="program_id">No Metadata Documentation available.</param>
        /// <param name="parent_id">No Metadata Documentation available.</param>
        public ObjectResult<sys_menu> sysGetUserMenuSp(Nullable<global::System.Int32> user_id, Nullable<global::System.Int32> program_id, Nullable<global::System.Int32> parent_id)
        {
            ObjectParameter user_idParameter;
            if (user_id.HasValue)
            {
                user_idParameter = new ObjectParameter("user_id", user_id);
            }
            else
            {
                user_idParameter = new ObjectParameter("user_id", typeof(global::System.Int32));
            }
    
            ObjectParameter program_idParameter;
            if (program_id.HasValue)
            {
                program_idParameter = new ObjectParameter("program_id", program_id);
            }
            else
            {
                program_idParameter = new ObjectParameter("program_id", typeof(global::System.Int32));
            }
    
            ObjectParameter parent_idParameter;
            if (parent_id.HasValue)
            {
                parent_idParameter = new ObjectParameter("parent_id", parent_id);
            }
            else
            {
                parent_idParameter = new ObjectParameter("parent_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sys_menu>("sysGetUserMenuSp", user_idParameter, program_idParameter, parent_idParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="user_id">No Metadata Documentation available.</param>
        /// <param name="program_id">No Metadata Documentation available.</param>
        /// <param name="parent_id">No Metadata Documentation available.</param>
        public ObjectResult<sys_menu> sysGetUserMenuSp(Nullable<global::System.Int32> user_id, Nullable<global::System.Int32> program_id, Nullable<global::System.Int32> parent_id, MergeOption mergeOption)
        {
            ObjectParameter user_idParameter;
            if (user_id.HasValue)
            {
                user_idParameter = new ObjectParameter("user_id", user_id);
            }
            else
            {
                user_idParameter = new ObjectParameter("user_id", typeof(global::System.Int32));
            }
    
            ObjectParameter program_idParameter;
            if (program_id.HasValue)
            {
                program_idParameter = new ObjectParameter("program_id", program_id);
            }
            else
            {
                program_idParameter = new ObjectParameter("program_id", typeof(global::System.Int32));
            }
    
            ObjectParameter parent_idParameter;
            if (parent_id.HasValue)
            {
                parent_idParameter = new ObjectParameter("parent_id", parent_id);
            }
            else
            {
                parent_idParameter = new ObjectParameter("parent_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sys_menu>("sysGetUserMenuSp", mergeOption, user_idParameter, program_idParameter, parent_idParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<sysGetNativeUsersSp_Result> sysGetNativeUsersSp()
        {
            return base.ExecuteFunction<sysGetNativeUsersSp_Result>("sysGetNativeUsersSp");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_attachment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_attachment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_attachment object.
        /// </summary>
        /// <param name="attachment_id">Initial value of the attachment_id property.</param>
        /// <param name="file_path">Initial value of the file_path property.</param>
        /// <param name="create_by">Initial value of the create_by property.</param>
        /// <param name="create_date">Initial value of the create_date property.</param>
        public static sys_attachment Createsys_attachment(global::System.Int32 attachment_id, global::System.String file_path, global::System.Int32 create_by, global::System.DateTime create_date)
        {
            sys_attachment sys_attachment = new sys_attachment();
            sys_attachment.attachment_id = attachment_id;
            sys_attachment.file_path = file_path;
            sys_attachment.create_by = create_by;
            sys_attachment.create_date = create_date;
            return sys_attachment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 attachment_id
        {
            get
            {
                return _attachment_id;
            }
            set
            {
                if (_attachment_id != value)
                {
                    Onattachment_idChanging(value);
                    ReportPropertyChanging("attachment_id");
                    _attachment_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("attachment_id");
                    Onattachment_idChanged();
                }
            }
        }
        private global::System.Int32 _attachment_id;
        partial void Onattachment_idChanging(global::System.Int32 value);
        partial void Onattachment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String file_path
        {
            get
            {
                return _file_path;
            }
            set
            {
                Onfile_pathChanging(value);
                ReportPropertyChanging("file_path");
                _file_path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("file_path");
                Onfile_pathChanged();
            }
        }
        private global::System.String _file_path;
        partial void Onfile_pathChanging(global::System.String value);
        partial void Onfile_pathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 create_by
        {
            get
            {
                return _create_by;
            }
            set
            {
                Oncreate_byChanging(value);
                ReportPropertyChanging("create_by");
                _create_by = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_by");
                Oncreate_byChanged();
            }
        }
        private global::System.Int32 _create_by;
        partial void Oncreate_byChanging(global::System.Int32 value);
        partial void Oncreate_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private global::System.DateTime _create_date;
        partial void Oncreate_dateChanging(global::System.DateTime value);
        partial void Oncreate_dateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_attachment_ref")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_attachment_ref : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_attachment_ref object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="ref_type">Initial value of the ref_type property.</param>
        /// <param name="ref_num">Initial value of the ref_num property.</param>
        /// <param name="attachment_id">Initial value of the attachment_id property.</param>
        public static sys_attachment_ref Createsys_attachment_ref(global::System.Int32 id, global::System.String ref_type, global::System.String ref_num, global::System.Int32 attachment_id)
        {
            sys_attachment_ref sys_attachment_ref = new sys_attachment_ref();
            sys_attachment_ref.id = id;
            sys_attachment_ref.ref_type = ref_type;
            sys_attachment_ref.ref_num = ref_num;
            sys_attachment_ref.attachment_id = attachment_id;
            return sys_attachment_ref;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ref_type
        {
            get
            {
                return _ref_type;
            }
            set
            {
                Onref_typeChanging(value);
                ReportPropertyChanging("ref_type");
                _ref_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ref_type");
                Onref_typeChanged();
            }
        }
        private global::System.String _ref_type;
        partial void Onref_typeChanging(global::System.String value);
        partial void Onref_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ref_num
        {
            get
            {
                return _ref_num;
            }
            set
            {
                Onref_numChanging(value);
                ReportPropertyChanging("ref_num");
                _ref_num = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ref_num");
                Onref_numChanged();
            }
        }
        private global::System.String _ref_num;
        partial void Onref_numChanging(global::System.String value);
        partial void Onref_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 attachment_id
        {
            get
            {
                return _attachment_id;
            }
            set
            {
                Onattachment_idChanging(value);
                ReportPropertyChanging("attachment_id");
                _attachment_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attachment_id");
                Onattachment_idChanged();
            }
        }
        private global::System.Int32 _attachment_id;
        partial void Onattachment_idChanging(global::System.Int32 value);
        partial void Onattachment_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_dept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_dept : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_dept object.
        /// </summary>
        /// <param name="deptid">Initial value of the deptid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static sys_dept Createsys_dept(global::System.Int32 deptid, global::System.String name)
        {
            sys_dept sys_dept = new sys_dept();
            sys_dept.deptid = deptid;
            sys_dept.name = name;
            return sys_dept;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 deptid
        {
            get
            {
                return _deptid;
            }
            set
            {
                if (_deptid != value)
                {
                    OndeptidChanging(value);
                    ReportPropertyChanging("deptid");
                    _deptid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("deptid");
                    OndeptidChanged();
                }
            }
        }
        private global::System.Int32 _deptid;
        partial void OndeptidChanging(global::System.Int32 value);
        partial void OndeptidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortname
        {
            get
            {
                return _shortname;
            }
            set
            {
                OnshortnameChanging(value);
                ReportPropertyChanging("shortname");
                _shortname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortname");
                OnshortnameChanged();
            }
        }
        private global::System.String _shortname;
        partial void OnshortnameChanging(global::System.String value);
        partial void OnshortnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> managerid
        {
            get
            {
                return _managerid;
            }
            set
            {
                OnmanageridChanging(value);
                ReportPropertyChanging("managerid");
                _managerid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("managerid");
                OnmanageridChanged();
            }
        }
        private Nullable<global::System.Int32> _managerid;
        partial void OnmanageridChanging(Nullable<global::System.Int32> value);
        partial void OnmanageridChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_group_menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_group_menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_group_menu object.
        /// </summary>
        /// <param name="group_id">Initial value of the group_id property.</param>
        /// <param name="menu_id">Initial value of the menu_id property.</param>
        public static sys_group_menu Createsys_group_menu(global::System.Int32 group_id, global::System.Int32 menu_id)
        {
            sys_group_menu sys_group_menu = new sys_group_menu();
            sys_group_menu.group_id = group_id;
            sys_group_menu.menu_id = menu_id;
            return sys_group_menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 group_id
        {
            get
            {
                return _group_id;
            }
            set
            {
                if (_group_id != value)
                {
                    Ongroup_idChanging(value);
                    ReportPropertyChanging("group_id");
                    _group_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("group_id");
                    Ongroup_idChanged();
                }
            }
        }
        private global::System.Int32 _group_id;
        partial void Ongroup_idChanging(global::System.Int32 value);
        partial void Ongroup_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menu_id
        {
            get
            {
                return _menu_id;
            }
            set
            {
                if (_menu_id != value)
                {
                    Onmenu_idChanging(value);
                    ReportPropertyChanging("menu_id");
                    _menu_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("menu_id");
                    Onmenu_idChanged();
                }
            }
        }
        private global::System.Int32 _menu_id;
        partial void Onmenu_idChanging(global::System.Int32 value);
        partial void Onmenu_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_menu object.
        /// </summary>
        /// <param name="menu_id">Initial value of the menu_id property.</param>
        /// <param name="program_id">Initial value of the program_id property.</param>
        /// <param name="node_id">Initial value of the node_id property.</param>
        /// <param name="expanded">Initial value of the expanded property.</param>
        /// <param name="leaf">Initial value of the leaf property.</param>
        public static sys_menu Createsys_menu(global::System.Int32 menu_id, global::System.Int32 program_id, global::System.String node_id, global::System.Boolean expanded, global::System.Boolean leaf)
        {
            sys_menu sys_menu = new sys_menu();
            sys_menu.menu_id = menu_id;
            sys_menu.program_id = program_id;
            sys_menu.node_id = node_id;
            sys_menu.expanded = expanded;
            sys_menu.leaf = leaf;
            return sys_menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menu_id
        {
            get
            {
                return _menu_id;
            }
            set
            {
                if (_menu_id != value)
                {
                    Onmenu_idChanging(value);
                    ReportPropertyChanging("menu_id");
                    _menu_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("menu_id");
                    Onmenu_idChanged();
                }
            }
        }
        private global::System.Int32 _menu_id;
        partial void Onmenu_idChanging(global::System.Int32 value);
        partial void Onmenu_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 program_id
        {
            get
            {
                return _program_id;
            }
            set
            {
                Onprogram_idChanging(value);
                ReportPropertyChanging("program_id");
                _program_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("program_id");
                Onprogram_idChanged();
            }
        }
        private global::System.Int32 _program_id;
        partial void Onprogram_idChanging(global::System.Int32 value);
        partial void Onprogram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String node_id
        {
            get
            {
                return _node_id;
            }
            set
            {
                Onnode_idChanging(value);
                ReportPropertyChanging("node_id");
                _node_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("node_id");
                Onnode_idChanged();
            }
        }
        private global::System.String _node_id;
        partial void Onnode_idChanging(global::System.String value);
        partial void Onnode_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_cn
        {
            get
            {
                return _text_cn;
            }
            set
            {
                Ontext_cnChanging(value);
                ReportPropertyChanging("text_cn");
                _text_cn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_cn");
                Ontext_cnChanged();
            }
        }
        private global::System.String _text_cn;
        partial void Ontext_cnChanging(global::System.String value);
        partial void Ontext_cnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parent_id
        {
            get
            {
                return _parent_id;
            }
            set
            {
                Onparent_idChanging(value);
                ReportPropertyChanging("parent_id");
                _parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent_id");
                Onparent_idChanged();
            }
        }
        private Nullable<global::System.Int32> _parent_id;
        partial void Onparent_idChanging(Nullable<global::System.Int32> value);
        partial void Onparent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean expanded
        {
            get
            {
                return _expanded;
            }
            set
            {
                OnexpandedChanging(value);
                ReportPropertyChanging("expanded");
                _expanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("expanded");
                OnexpandedChanged();
            }
        }
        private global::System.Boolean _expanded;
        partial void OnexpandedChanging(global::System.Boolean value);
        partial void OnexpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean leaf
        {
            get
            {
                return _leaf;
            }
            set
            {
                OnleafChanging(value);
                ReportPropertyChanging("leaf");
                _leaf = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("leaf");
                OnleafChanged();
            }
        }
        private global::System.Boolean _leaf;
        partial void OnleafChanging(global::System.Boolean value);
        partial void OnleafChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icon_class
        {
            get
            {
                return _icon_class;
            }
            set
            {
                Onicon_classChanging(value);
                ReportPropertyChanging("icon_class");
                _icon_class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icon_class");
                Onicon_classChanged();
            }
        }
        private global::System.String _icon_class;
        partial void Onicon_classChanging(global::System.String value);
        partial void Onicon_classChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String href
        {
            get
            {
                return _href;
            }
            set
            {
                OnhrefChanging(value);
                ReportPropertyChanging("href");
                _href = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("href");
                OnhrefChanged();
            }
        }
        private global::System.String _href;
        partial void OnhrefChanging(global::System.String value);
        partial void OnhrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String href_target
        {
            get
            {
                return _href_target;
            }
            set
            {
                Onhref_targetChanging(value);
                ReportPropertyChanging("href_target");
                _href_target = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("href_target");
                Onhref_targetChanged();
            }
        }
        private global::System.String _href_target;
        partial void Onhref_targetChanging(global::System.String value);
        partial void Onhref_targetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> seq
        {
            get
            {
                return _seq;
            }
            set
            {
                OnseqChanging(value);
                ReportPropertyChanging("seq");
                _seq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("seq");
                OnseqChanged();
            }
        }
        private Nullable<global::System.Int32> _seq;
        partial void OnseqChanging(Nullable<global::System.Int32> value);
        partial void OnseqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String component_alias
        {
            get
            {
                return _component_alias;
            }
            set
            {
                Oncomponent_aliasChanging(value);
                ReportPropertyChanging("component_alias");
                _component_alias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("component_alias");
                Oncomponent_aliasChanged();
            }
        }
        private global::System.String _component_alias;
        partial void Oncomponent_aliasChanging(global::System.String value);
        partial void Oncomponent_aliasChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_program")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_program : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_program object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="program_name">Initial value of the program_name property.</param>
        public static sys_program Createsys_program(global::System.Int32 id, global::System.String program_name)
        {
            sys_program sys_program = new sys_program();
            sys_program.id = id;
            sys_program.program_name = program_name;
            return sys_program;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String program_name
        {
            get
            {
                return _program_name;
            }
            set
            {
                Onprogram_nameChanging(value);
                ReportPropertyChanging("program_name");
                _program_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("program_name");
                Onprogram_nameChanged();
            }
        }
        private global::System.String _program_name;
        partial void Onprogram_nameChanging(global::System.String value);
        partial void Onprogram_nameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_strings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_strings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_strings object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static sys_strings Createsys_strings(global::System.Int32 id)
        {
            sys_strings sys_strings = new sys_strings();
            sys_strings.id = id;
            return sys_strings;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> program_id
        {
            get
            {
                return _program_id;
            }
            set
            {
                Onprogram_idChanging(value);
                ReportPropertyChanging("program_id");
                _program_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("program_id");
                Onprogram_idChanged();
            }
        }
        private Nullable<global::System.Int32> _program_id;
        partial void Onprogram_idChanging(Nullable<global::System.Int32> value);
        partial void Onprogram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String object_name
        {
            get
            {
                return _object_name;
            }
            set
            {
                Onobject_nameChanging(value);
                ReportPropertyChanging("object_name");
                _object_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("object_name");
                Onobject_nameChanged();
            }
        }
        private global::System.String _object_name;
        partial void Onobject_nameChanging(global::System.String value);
        partial void Onobject_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String en_string
        {
            get
            {
                return _en_string;
            }
            set
            {
                Onen_stringChanging(value);
                ReportPropertyChanging("en_string");
                _en_string = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("en_string");
                Onen_stringChanged();
            }
        }
        private global::System.String _en_string;
        partial void Onen_stringChanging(global::System.String value);
        partial void Onen_stringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cn_string
        {
            get
            {
                return _cn_string;
            }
            set
            {
                Oncn_stringChanging(value);
                ReportPropertyChanging("cn_string");
                _cn_string = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cn_string");
                Oncn_stringChanged();
            }
        }
        private global::System.String _cn_string;
        partial void Oncn_stringChanging(global::System.String value);
        partial void Oncn_stringChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_user object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="sso">Initial value of the sso property.</param>
        /// <param name="name_cn">Initial value of the name_cn property.</param>
        /// <param name="name_en">Initial value of the name_en property.</param>
        /// <param name="login_pwd">Initial value of the login_pwd property.</param>
        /// <param name="account_status">Initial value of the account_status property.</param>
        public static sys_user Createsys_user(global::System.Int32 user_id, global::System.String sso, global::System.String name_cn, global::System.String name_en, global::System.String login_pwd, global::System.Int32 account_status)
        {
            sys_user sys_user = new sys_user();
            sys_user.user_id = user_id;
            sys_user.sso = sso;
            sys_user.name_cn = name_cn;
            sys_user.name_en = name_en;
            sys_user.login_pwd = login_pwd;
            sys_user.account_status = account_status;
            return sys_user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sso
        {
            get
            {
                return _sso;
            }
            set
            {
                OnssoChanging(value);
                ReportPropertyChanging("sso");
                _sso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sso");
                OnssoChanged();
            }
        }
        private global::System.String _sso;
        partial void OnssoChanging(global::System.String value);
        partial void OnssoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name_cn
        {
            get
            {
                return _name_cn;
            }
            set
            {
                Onname_cnChanging(value);
                ReportPropertyChanging("name_cn");
                _name_cn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name_cn");
                Onname_cnChanged();
            }
        }
        private global::System.String _name_cn;
        partial void Onname_cnChanging(global::System.String value);
        partial void Onname_cnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name_en
        {
            get
            {
                return _name_en;
            }
            set
            {
                Onname_enChanging(value);
                ReportPropertyChanging("name_en");
                _name_en = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name_en");
                Onname_enChanged();
            }
        }
        private global::System.String _name_en;
        partial void Onname_enChanging(global::System.String value);
        partial void Onname_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login_pwd
        {
            get
            {
                return _login_pwd;
            }
            set
            {
                Onlogin_pwdChanging(value);
                ReportPropertyChanging("login_pwd");
                _login_pwd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login_pwd");
                Onlogin_pwdChanged();
            }
        }
        private global::System.String _login_pwd;
        partial void Onlogin_pwdChanging(global::System.String value);
        partial void Onlogin_pwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 account_status
        {
            get
            {
                return _account_status;
            }
            set
            {
                Onaccount_statusChanging(value);
                ReportPropertyChanging("account_status");
                _account_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("account_status");
                Onaccount_statusChanged();
            }
        }
        private global::System.Int32 _account_status;
        partial void Onaccount_statusChanging(global::System.Int32 value);
        partial void Onaccount_statusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_user_group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_user_group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_user_group object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="group_id">Initial value of the group_id property.</param>
        public static sys_user_group Createsys_user_group(global::System.Int32 user_id, global::System.Int32 group_id)
        {
            sys_user_group sys_user_group = new sys_user_group();
            sys_user_group.user_id = user_id;
            sys_user_group.group_id = group_id;
            return sys_user_group;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 group_id
        {
            get
            {
                return _group_id;
            }
            set
            {
                if (_group_id != value)
                {
                    Ongroup_idChanging(value);
                    ReportPropertyChanging("group_id");
                    _group_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("group_id");
                    Ongroup_idChanged();
                }
            }
        }
        private global::System.Int32 _group_id;
        partial void Ongroup_idChanging(global::System.Int32 value);
        partial void Ongroup_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sys_user_menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_user_menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sys_user_menu object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="menu_id">Initial value of the menu_id property.</param>
        public static sys_user_menu Createsys_user_menu(global::System.Int32 user_id, global::System.Int32 menu_id)
        {
            sys_user_menu sys_user_menu = new sys_user_menu();
            sys_user_menu.user_id = user_id;
            sys_user_menu.menu_id = menu_id;
            return sys_user_menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menu_id
        {
            get
            {
                return _menu_id;
            }
            set
            {
                if (_menu_id != value)
                {
                    Onmenu_idChanging(value);
                    ReportPropertyChanging("menu_id");
                    _menu_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("menu_id");
                    Onmenu_idChanged();
                }
            }
        }
        private global::System.Int32 _menu_id;
        partial void Onmenu_idChanging(global::System.Int32 value);
        partial void Onmenu_idChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="LoginUser")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class LoginUser : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_login_flag
        {
            get
            {
                return _C_login_flag;
            }
            set
            {
                OnC_login_flagChanging(value);
                ReportPropertyChanging("C_login_flag");
                _C_login_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_login_flag");
                OnC_login_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _C_login_flag;
        partial void OnC_login_flagChanging(Nullable<global::System.Int32> value);
        partial void OnC_login_flagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_employeeid
        {
            get
            {
                return _C_employeeid;
            }
            set
            {
                OnC_employeeidChanging(value);
                ReportPropertyChanging("C_employeeid");
                _C_employeeid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_employeeid");
                OnC_employeeidChanged();
            }
        }
        private Nullable<global::System.Int32> _C_employeeid;
        partial void OnC_employeeidChanging(Nullable<global::System.Int32> value);
        partial void OnC_employeeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_local_id
        {
            get
            {
                return _C_local_id;
            }
            set
            {
                OnC_local_idChanging(value);
                ReportPropertyChanging("C_local_id");
                _C_local_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_local_id");
                OnC_local_idChanged();
            }
        }
        private global::System.String _C_local_id;
        partial void OnC_local_idChanging(global::System.String value);
        partial void OnC_local_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_sso
        {
            get
            {
                return _C_sso;
            }
            set
            {
                OnC_ssoChanging(value);
                ReportPropertyChanging("C_sso");
                _C_sso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_sso");
                OnC_ssoChanged();
            }
        }
        private global::System.String _C_sso;
        partial void OnC_ssoChanging(global::System.String value);
        partial void OnC_ssoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_cname
        {
            get
            {
                return _C_cname;
            }
            set
            {
                OnC_cnameChanging(value);
                ReportPropertyChanging("C_cname");
                _C_cname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_cname");
                OnC_cnameChanged();
            }
        }
        private global::System.String _C_cname;
        partial void OnC_cnameChanging(global::System.String value);
        partial void OnC_cnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_ename
        {
            get
            {
                return _C_ename;
            }
            set
            {
                OnC_enameChanging(value);
                ReportPropertyChanging("C_ename");
                _C_ename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_ename");
                OnC_enameChanged();
            }
        }
        private global::System.String _C_ename;
        partial void OnC_enameChanging(global::System.String value);
        partial void OnC_enameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_department_id
        {
            get
            {
                return _C_department_id;
            }
            set
            {
                OnC_department_idChanging(value);
                ReportPropertyChanging("C_department_id");
                _C_department_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_department_id");
                OnC_department_idChanged();
            }
        }
        private Nullable<global::System.Int32> _C_department_id;
        partial void OnC_department_idChanging(Nullable<global::System.Int32> value);
        partial void OnC_department_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_loginpwd
        {
            get
            {
                return _C_loginpwd;
            }
            set
            {
                OnC_loginpwdChanging(value);
                ReportPropertyChanging("C_loginpwd");
                _C_loginpwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_loginpwd");
                OnC_loginpwdChanged();
            }
        }
        private global::System.String _C_loginpwd;
        partial void OnC_loginpwdChanging(global::System.String value);
        partial void OnC_loginpwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_account_stat
        {
            get
            {
                return _C_account_stat;
            }
            set
            {
                OnC_account_statChanging(value);
                ReportPropertyChanging("C_account_stat");
                _C_account_stat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_account_stat");
                OnC_account_statChanged();
            }
        }
        private Nullable<global::System.Int32> _C_account_stat;
        partial void OnC_account_statChanging(Nullable<global::System.Int32> value);
        partial void OnC_account_statChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SZIntraV3_1_WebSite.Models.EntityModel.SystemAdminModel", Name="sysGetNativeUsersSp_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sysGetNativeUsersSp_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysGetNativeUsersSp_Result object.
        /// </summary>
        /// <param name="employee_id">Initial value of the employee_id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static sysGetNativeUsersSp_Result CreatesysGetNativeUsersSp_Result(global::System.Int32 employee_id, global::System.Int32 user_id)
        {
            sysGetNativeUsersSp_Result sysGetNativeUsersSp_Result = new sysGetNativeUsersSp_Result();
            sysGetNativeUsersSp_Result.employee_id = employee_id;
            sysGetNativeUsersSp_Result.user_id = user_id;
            return sysGetNativeUsersSp_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employee_id
        {
            get
            {
                return _employee_id;
            }
            set
            {
                Onemployee_idChanging(value);
                ReportPropertyChanging("employee_id");
                _employee_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("employee_id");
                Onemployee_idChanged();
            }
        }
        private global::System.Int32 _employee_id;
        partial void Onemployee_idChanging(global::System.Int32 value);
        partial void Onemployee_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String local_id
        {
            get
            {
                return _local_id;
            }
            set
            {
                Onlocal_idChanging(value);
                ReportPropertyChanging("local_id");
                _local_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("local_id");
                Onlocal_idChanged();
            }
        }
        private global::System.String _local_id;
        partial void Onlocal_idChanging(global::System.String value);
        partial void Onlocal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_cn
        {
            get
            {
                return _name_cn;
            }
            set
            {
                Onname_cnChanging(value);
                ReportPropertyChanging("name_cn");
                _name_cn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_cn");
                Onname_cnChanged();
            }
        }
        private global::System.String _name_cn;
        partial void Onname_cnChanging(global::System.String value);
        partial void Onname_cnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_en
        {
            get
            {
                return _name_en;
            }
            set
            {
                Onname_enChanging(value);
                ReportPropertyChanging("name_en");
                _name_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_en");
                Onname_enChanged();
            }
        }
        private global::System.String _name_en;
        partial void Onname_enChanging(global::System.String value);
        partial void Onname_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sso
        {
            get
            {
                return _sso;
            }
            set
            {
                OnssoChanging(value);
                ReportPropertyChanging("sso");
                _sso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sso");
                OnssoChanged();
            }
        }
        private global::System.String _sso;
        partial void OnssoChanging(global::System.String value);
        partial void OnssoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();

        #endregion
    }

    #endregion
    
}
